#!/bin/bash
# PRIME Indicator - indicator applet for NVIDIA Optimus laptops
# Copyright (C) 2013 Alfred Neumayer
# Copyright (C) 2016 André Brait
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

if [[ $1 == "intel" ]]
then
    prime-select intel &>/dev/null
    sync
else
    if [[ -z $2 ]]
    then
        prime-select nvidia &>/dev/null
        sync
    elif [[ $2 == "on" ]]
    then
        modprobe nvidia_drm nvidia_modeset nvidia_uvm nvidia &>/dev/null
        tee /proc/acpi/bbswitch <<< ON &>/dev/null
    else
        rmmod nvidia_drm nvidia_modeset nvidia_uvm nvidia &>/dev/null
        tee /proc/acpi/bbswitch <<< OFF &>/dev/null
    fi
fi
